- id: black
  name: black
  description: "Black: The uncompromising Python code formatter"
  entry: black
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]

- id: flake8
  name: flake8
  description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
  entry: flake8
  language: python
  types: [python]
  require_serial: true

- id: isort
  name: isort
  entry: isort
  require_serial: true
  language: python
  types_or: [cython, pyi, python]
  args: ['--filter-files']
  minimum_pre_commit_version: '2.9.2'

- id: pyupgrade
  alias: format
  name: pyupgrade
  description: Automatically upgrade syntax for newer versions.
  entry: pyupgrade
  args: [--py39-plus]
  language: system
  types: [python]
  minimum_pre_commit_version: 0.15.0

- id: bandit
  name: bandit
  description: 'Bandit is a tool for finding common security issues in Python code'
  entry: bandit
  language: python
  language_version: python3
  types: [python]
  args: [--quiet, --format=custom, --configfile=.bandit]

- id: mypy
  alias: lint
  name: mypy
  entry: mypy
  language: system
  types: [python]
  require_serial: true
